=encoding utf8

=head1 ABOUT

This repository contains the perl 5 segfault reproduction
recipe by mahmoud from Freenode's #perl channel.

Some tweaks were made to it by Shlomi Fish and it no longer requires
File-Slurp.

=head1 STEPS TO REPRODUCE

1. cd to the directory of the repository (that contains "lol.pl").

2. Run lol.pl:

    perl lol.pl

=cut

